name: Release DataWeave Native CLI
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:

  # This workflow contains a single job called "build"
  RELEASE_EXTENSION:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            script_name: windows
          - os: ubuntu-latest
            script_name: linux
          - os: macos-latest
            script_name: osx

    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Read graalvm version
      - name: Read Graalvm version
        run: |
          echo "GRAALVM_VERSION=$(grep graalvmVersion gradle.properties | cut -d '=' -f2)" >> $GITHUB_ENV
        shell: bash
      
      # Setup Graalvm
      - name: Setup Graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{env.GRAALVM_VERSION}}
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Guess Extension Version
        run: |
          echo "NATIVE_VERSION=$(echo '${{github.ref}}' | sed -e 's,.*/v\(.*\),\1,')" >> $GITHUB_ENV
        shell: bash
      
      # Runs a single command using the runners shell
      - name: Run Build
        run: |
          ./gradlew build -PnativeVersion=${{env.NATIVE_VERSION}}
        shell: bash
      
      # Generate distro
      - name: Create Distro
        run: ./gradlew native-cli:distro -PnativeVersion=${{env.NATIVE_VERSION}}
        shell: bash

      # Upload the artifact file
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: native-cli/build/distributions/native-cli-${{env.NATIVE_VERSION}}-native-distro-${{ matrix.script_name }}.zip
          asset_name: dw-${{env.NATIVE_VERSION}}-${{runner.os}}
          tag: ${{ github.ref }}
          overwrite: true

